[package]
name = "rust_test"
version = "0.1.0"
authors = ["ogiwara <yushiogiwara@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
by_address = "1.0.4"